/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author FamTerrazas
 */
public class ViewUsuario extends javax.swing.JPanel {

    /**
     * Creates new form ViewUsuario
     */
    public ViewUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_nombre = new javax.swing.JLabel();
        jL_usuario = new javax.swing.JLabel();
        jL_password = new javax.swing.JLabel();
        jL_nivel = new javax.swing.JLabel();
        jL_estado = new javax.swing.JLabel();
        jtf_nombre = new javax.swing.JTextField();
        jtf_usuario = new javax.swing.JTextField();
        jtf_password = new javax.swing.JTextField();
        jcb_nivel = new javax.swing.JComboBox();
        jcb_estado = new javax.swing.JComboBox();
        jL_imagen = new javax.swing.JLabel();
        jB_primero = new javax.swing.JButton();
        jB_anterior = new javax.swing.JButton();
        jB_siguiente = new javax.swing.JButton();
        jB_ultimo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_usuario = new javax.swing.JTable();
        jB_nuevo = new javax.swing.JButton();
        jB_editar = new javax.swing.JButton();
        jB_eliminar = new javax.swing.JButton();
        jB_guardar = new javax.swing.JButton();

        jL_nombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jL_nombre.setText("Nombre");

        jL_usuario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jL_usuario.setText("Usuario");

        jL_password.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jL_password.setText("Contraseña");

        jL_nivel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jL_nivel.setText("Nivel");

        jL_estado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jL_estado.setText("Estado");

        jtf_nombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jtf_usuario.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jtf_password.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jcb_nivel.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jcb_nivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Vendedor", "Root" }));

        jcb_estado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jcb_estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));

        jL_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usuario.png"))); // NOI18N

        jB_primero.setText("|<");

        jB_anterior.setText("<");

        jB_siguiente.setText(">");

        jB_ultimo.setText(">|");

        jT_usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Usuario", "Nivel", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jT_usuario);

        jB_nuevo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jB_nuevo.setText("Nuevo");

        jB_editar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jB_editar.setText("Editar");

        jB_eliminar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jB_eliminar.setText("Eliminar");

        jB_guardar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jB_guardar.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL_imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jL_usuario)
                                        .addComponent(jL_nombre))
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtf_usuario)
                                        .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jL_nivel)
                                        .addComponent(jL_estado))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jcb_nivel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jcb_estado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jB_primero)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jB_anterior))
                                                .addComponent(jB_nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jB_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(47, 47, 47)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jB_siguiente)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jB_ultimo))
                                                .addComponent(jB_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jB_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addComponent(jL_password)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_nombre)
                            .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_usuario)
                            .addComponent(jtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_password)
                            .addComponent(jtf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jcb_nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jL_nivel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jL_estado)))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB_primero)
                            .addComponent(jB_anterior)
                            .addComponent(jB_siguiente)
                            .addComponent(jB_ultimo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB_nuevo)
                            .addComponent(jB_guardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB_editar)
                            .addComponent(jB_eliminar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jB_anterior;
    public javax.swing.JButton jB_editar;
    public javax.swing.JButton jB_eliminar;
    public javax.swing.JButton jB_guardar;
    public javax.swing.JButton jB_nuevo;
    public javax.swing.JButton jB_primero;
    public javax.swing.JButton jB_siguiente;
    public javax.swing.JButton jB_ultimo;
    public javax.swing.JLabel jL_estado;
    private javax.swing.JLabel jL_imagen;
    public javax.swing.JLabel jL_nivel;
    public javax.swing.JLabel jL_nombre;
    public javax.swing.JLabel jL_password;
    public javax.swing.JLabel jL_usuario;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jT_usuario;
    public javax.swing.JComboBox jcb_estado;
    public javax.swing.JComboBox jcb_nivel;
    public javax.swing.JTextField jtf_nombre;
    public javax.swing.JTextField jtf_password;
    public javax.swing.JTextField jtf_usuario;
    // End of variables declaration//GEN-END:variables
}
