/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import javax.swing.JOptionPane;

/**
 *
 * @author Karla Terrazas
 */
public class ViewMain extends javax.swing.JFrame {

    /**
     * Creates new form ViewMain
     */
    public ViewMain() {
        initComponents();
    }

    public void cerrar(){
    Object [] opciones ={"Aceptar","Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane,"¿Deseas cerrar la aplicación?","Mensaje de Confirmacion",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
            if (eleccion == JOptionPane.YES_OPTION)
            {
            System.exit(0);
        }else{
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_imagen1 = new javax.swing.JLabel();
        jL_imagen2 = new javax.swing.JLabel();
        jL_usuario = new javax.swing.JLabel();
        jL_pasword = new javax.swing.JLabel();
        jft_usuario = new javax.swing.JTextField();
        jtf_password = new javax.swing.JTextField();
        jL_inicio = new javax.swing.JLabel();
        jB_entrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jM_archivo = new javax.swing.JMenu();
        jmi_usuarios = new javax.swing.JMenuItem();
        jM_catalogos = new javax.swing.JMenu();
        jmi_clientes = new javax.swing.JMenuItem();
        jmi_proveedores = new javax.swing.JMenuItem();
        jmi_productos = new javax.swing.JMenuItem();
        jM_operaciones = new javax.swing.JMenu();
        jmi_compras = new javax.swing.JMenuItem();
        jmi_ventas = new javax.swing.JMenuItem();
        jM_reportes = new javax.swing.JMenu();
        jmi_clientess = new javax.swing.JMenuItem();
        jmi_productoss = new javax.swing.JMenuItem();
        jmi_proveedoress = new javax.swing.JMenuItem();
        jmi_comprass = new javax.swing.JMenuItem();
        jmi_ventass = new javax.swing.JMenuItem();
        jM_ayuda = new javax.swing.JMenu();
        jmi_acerca_de = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jL_imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dulce.png"))); // NOI18N

        jL_imagen2.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jL_imagen2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/candy.png"))); // NOI18N
        jL_imagen2.setLabelFor(jL_imagen2);
        jL_imagen2.setText("D U L C E R I A");
        jL_imagen2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jL_usuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jL_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_usuario.setText("Usuario");

        jL_pasword.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jL_pasword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_pasword.setText("Contraseña");

        jft_usuario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jtf_password.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jL_inicio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jL_inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_inicio.setText("Inicio \nSesión");

        jB_entrar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jB_entrar.setText("Entrar");
        jB_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_entrarActionPerformed(evt);
            }
        });

        jM_archivo.setText("Archivo");
        jM_archivo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jmi_usuarios.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jmi_usuarios.setText("Usuarios");
        jM_archivo.add(jmi_usuarios);

        jMenuBar1.add(jM_archivo);

        jM_catalogos.setText("Catalogos");
        jM_catalogos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jmi_clientes.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jmi_clientes.setText("Clientes");
        jM_catalogos.add(jmi_clientes);

        jmi_proveedores.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jmi_proveedores.setText("Proveedores");
        jM_catalogos.add(jmi_proveedores);

        jmi_productos.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jmi_productos.setText("Productos");
        jM_catalogos.add(jmi_productos);

        jMenuBar1.add(jM_catalogos);

        jM_operaciones.setText("Operaciones");
        jM_operaciones.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jmi_compras.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jmi_compras.setText("Compras");
        jM_operaciones.add(jmi_compras);

        jmi_ventas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jmi_ventas.setText("Ventas");
        jM_operaciones.add(jmi_ventas);

        jMenuBar1.add(jM_operaciones);

        jM_reportes.setText("Reportes");
        jM_reportes.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jmi_clientess.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jmi_clientess.setText("Clientes");
        jmi_clientess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_clientessActionPerformed(evt);
            }
        });
        jM_reportes.add(jmi_clientess);

        jmi_productoss.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jmi_productoss.setText("Productos");
        jmi_productoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_productossActionPerformed(evt);
            }
        });
        jM_reportes.add(jmi_productoss);

        jmi_proveedoress.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jmi_proveedoress.setText("Proveedores");
        jM_reportes.add(jmi_proveedoress);

        jmi_comprass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jmi_comprass.setText("Compras");
        jM_reportes.add(jmi_comprass);

        jmi_ventass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jmi_ventass.setText("Ventas");
        jM_reportes.add(jmi_ventass);

        jMenuBar1.add(jM_reportes);

        jM_ayuda.setText("Ayuda");
        jM_ayuda.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jmi_acerca_de.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jmi_acerca_de.setText("Acerca de");
        jM_ayuda.add(jmi_acerca_de);

        jMenuBar1.add(jM_ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_imagen1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jL_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jL_pasword)
                                    .addComponent(jL_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jft_usuario)
                                    .addComponent(jtf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(58, 58, 58)
                            .addComponent(jB_entrar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jL_imagen2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL_imagen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL_inicio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_usuario)
                            .addComponent(jft_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_pasword)
                            .addComponent(jtf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jB_entrar)
                        .addGap(18, 18, 18)
                        .addComponent(jL_imagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_clientessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_clientessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_clientessActionPerformed

    private void jmi_productossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_productossActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_productossActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    cerrar();   // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void jB_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_entrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jB_entrar;
    private javax.swing.JLabel jL_imagen1;
    private javax.swing.JLabel jL_imagen2;
    private javax.swing.JLabel jL_inicio;
    public javax.swing.JLabel jL_pasword;
    public javax.swing.JLabel jL_usuario;
    public javax.swing.JMenu jM_archivo;
    public javax.swing.JMenu jM_ayuda;
    public javax.swing.JMenu jM_catalogos;
    public javax.swing.JMenu jM_operaciones;
    public javax.swing.JMenu jM_reportes;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JTextField jft_usuario;
    public javax.swing.JMenuItem jmi_acerca_de;
    public javax.swing.JMenuItem jmi_clientes;
    public javax.swing.JMenuItem jmi_clientess;
    public javax.swing.JMenuItem jmi_compras;
    public javax.swing.JMenuItem jmi_comprass;
    public javax.swing.JMenuItem jmi_productos;
    public javax.swing.JMenuItem jmi_productoss;
    public javax.swing.JMenuItem jmi_proveedores;
    public javax.swing.JMenuItem jmi_proveedoress;
    public javax.swing.JMenuItem jmi_usuarios;
    public javax.swing.JMenuItem jmi_ventas;
    public javax.swing.JMenuItem jmi_ventass;
    public javax.swing.JTextField jtf_password;
    // End of variables declaration//GEN-END:variables

}