/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author FamTerrazas
 */
public class ViewProveedor extends javax.swing.JPanel {

    /**
     * Creates new form ViewProveedor
     */
    public ViewProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jL_proveedores = new javax.swing.JLabel();
        jL_id = new javax.swing.JLabel();
        jL_nombre = new javax.swing.JLabel();
        jL_rfc = new javax.swing.JLabel();
        jL_calle = new javax.swing.JLabel();
        jL_no = new javax.swing.JLabel();
        jL_colonia = new javax.swing.JLabel();
        jL_ciudad = new javax.swing.JLabel();
        jL_estado = new javax.swing.JLabel();
        jL_nombre_contacto = new javax.swing.JLabel();
        jL_telefono = new javax.swing.JLabel();
        jL_email = new javax.swing.JLabel();
        jtf_id = new javax.swing.JTextField();
        jtf_rfc = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_calle = new javax.swing.JTextField();
        jtf_colonia = new javax.swing.JTextField();
        jtf_no = new javax.swing.JTextField();
        jtf_ciudad = new javax.swing.JTextField();
        jtf_estado = new javax.swing.JTextField();
        jtf_nombre_contacto = new javax.swing.JTextField();
        jtf_telefono = new javax.swing.JTextField();
        jtf_email = new javax.swing.JTextField();
        jB_primero = new javax.swing.JButton();
        jB_anterior = new javax.swing.JButton();
        jB_siguiente = new javax.swing.JButton();
        jB_ultimo = new javax.swing.JButton();
        jB_agregar = new javax.swing.JButton();
        jB_quitar = new javax.swing.JButton();
        jB_editar = new javax.swing.JButton();
        jB_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_tabla = new javax.swing.JTable();

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jL_proveedores.setBackground(new java.awt.Color(255, 255, 255));
        jL_proveedores.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jL_proveedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_proveedores.setText("PROVEEDORES");
        jL_proveedores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jL_id.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jL_id.setText("id_proveedor");

        jL_nombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jL_nombre.setText("Nombre");

        jL_rfc.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jL_rfc.setText("RFC");

        jL_calle.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jL_calle.setText("Calle");

        jL_no.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jL_no.setText("No");

        jL_colonia.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jL_colonia.setText("Colonia");

        jL_ciudad.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jL_ciudad.setText("Ciudad");

        jL_estado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jL_estado.setText("Estado");

        jL_nombre_contacto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jL_nombre_contacto.setText("Nombre contacto");

        jL_telefono.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jL_telefono.setText("Telefono");

        jL_email.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jL_email.setText("Email");

        jtf_id.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_idActionPerformed(evt);
            }
        });

        jtf_rfc.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtf_rfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_rfcActionPerformed(evt);
            }
        });

        jtf_nombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtf_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombreActionPerformed(evt);
            }
        });

        jtf_calle.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtf_calle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_calleActionPerformed(evt);
            }
        });

        jtf_colonia.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtf_colonia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_coloniaActionPerformed(evt);
            }
        });

        jtf_no.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtf_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_noActionPerformed(evt);
            }
        });

        jtf_ciudad.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtf_ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_ciudadActionPerformed(evt);
            }
        });

        jtf_estado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtf_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_estadoActionPerformed(evt);
            }
        });

        jtf_nombre_contacto.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtf_nombre_contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nombre_contactoActionPerformed(evt);
            }
        });

        jtf_telefono.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtf_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_telefonoActionPerformed(evt);
            }
        });

        jtf_email.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jtf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_emailActionPerformed(evt);
            }
        });

        jB_primero.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jB_primero.setText("|<");
        jB_primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_primeroActionPerformed(evt);
            }
        });

        jB_anterior.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jB_anterior.setText("<");

        jB_siguiente.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jB_siguiente.setText(">");

        jB_ultimo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jB_ultimo.setText("|>");

        jB_agregar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jB_agregar.setText("+");
        jB_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_agregarActionPerformed(evt);
            }
        });

        jB_quitar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jB_quitar.setText("-");
        jB_quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_quitarActionPerformed(evt);
            }
        });

        jB_editar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jB_editar.setText("Editar");

        jB_buscar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jB_buscar.setText("Buscar");

        jT_tabla.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jT_tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id_proveedor", "Nombre", "RFC", "Calle", "No", "Colonia", "..."
            }
        ));
        jScrollPane1.setViewportView(jT_tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_proveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jL_nombre)
                                                .addComponent(jL_rfc)
                                                .addComponent(jL_calle)
                                                .addComponent(jL_no)
                                                .addComponent(jL_colonia)
                                                .addComponent(jL_estado)
                                                .addComponent(jL_nombre_contacto)
                                                .addComponent(jL_telefono)
                                                .addComponent(jL_email)
                                                .addComponent(jL_id))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jL_ciudad)
                                                .addGap(68, 68, 68)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtf_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_nombre_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_no, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_calle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jB_agregar)
                                            .addComponent(jB_editar)
                                            .addComponent(jB_buscar)
                                            .addComponent(jB_quitar)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jB_primero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jB_anterior)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jB_siguiente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jB_ultimo)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jB_agregar)
                        .addGap(11, 11, 11)
                        .addComponent(jB_quitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtf_colonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jL_colonia)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jL_id)
                                            .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jL_nombre)
                                            .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jL_rfc)
                                            .addComponent(jtf_rfc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(14, 14, 14)
                                        .addComponent(jtf_calle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addComponent(jL_calle)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jL_no))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_ciudad)
                            .addComponent(jtf_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jL_estado)
                                    .addComponent(jtf_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jL_nombre_contacto))
                            .addComponent(jtf_nombre_contacto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_telefono))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jL_email)
                            .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_primero)
                    .addComponent(jB_anterior)
                    .addComponent(jB_siguiente)
                    .addComponent(jB_ultimo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_idActionPerformed

    private void jtf_rfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_rfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_rfcActionPerformed

    private void jtf_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nombreActionPerformed

    private void jtf_calleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_calleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_calleActionPerformed

    private void jtf_coloniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_coloniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_coloniaActionPerformed

    private void jtf_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_noActionPerformed

    private void jtf_ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_ciudadActionPerformed

    private void jtf_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_estadoActionPerformed

    private void jtf_nombre_contactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nombre_contactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nombre_contactoActionPerformed

    private void jtf_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_telefonoActionPerformed

    private void jtf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_emailActionPerformed

    private void jB_primeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_primeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_primeroActionPerformed

    private void jB_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_agregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_agregarActionPerformed

    private void jB_quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_quitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_quitarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jB_agregar;
    public javax.swing.JButton jB_anterior;
    public javax.swing.JButton jB_buscar;
    public javax.swing.JButton jB_editar;
    public javax.swing.JButton jB_primero;
    public javax.swing.JButton jB_quitar;
    public javax.swing.JButton jB_siguiente;
    public javax.swing.JButton jB_ultimo;
    public javax.swing.JLabel jL_calle;
    public javax.swing.JLabel jL_ciudad;
    public javax.swing.JLabel jL_colonia;
    public javax.swing.JLabel jL_email;
    public javax.swing.JLabel jL_estado;
    public javax.swing.JLabel jL_id;
    public javax.swing.JLabel jL_no;
    public javax.swing.JLabel jL_nombre;
    public javax.swing.JLabel jL_nombre_contacto;
    public javax.swing.JLabel jL_proveedores;
    public javax.swing.JLabel jL_rfc;
    public javax.swing.JLabel jL_telefono;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable jT_tabla;
    public javax.swing.JTextField jtf_calle;
    public javax.swing.JTextField jtf_ciudad;
    public javax.swing.JTextField jtf_colonia;
    public javax.swing.JTextField jtf_email;
    public javax.swing.JTextField jtf_estado;
    public javax.swing.JTextField jtf_id;
    public javax.swing.JTextField jtf_no;
    public javax.swing.JTextField jtf_nombre;
    public javax.swing.JTextField jtf_nombre_contacto;
    public javax.swing.JTextField jtf_rfc;
    public javax.swing.JTextField jtf_telefono;
    // End of variables declaration//GEN-END:variables
}
